// dynamicExtras.js — GENERIC engine.
// Every per-template layout.js only knows how to render the sections/photo it
// shipped with (hardcoded). Whatever the user adds at runtime — a custom
// section, an extra photo, a whole extra page — is rendered HERE instead,
// generically, using that template's own THEME (colors/font/border, see
// themes.js) so it blends in rather than looking like a bolted-on box.
// Extra PHOTOS are rendered as a freeform, absolutely-positioned overlay
// (draggable/resizable — see livePreview.js) so they never disturb a
// template's own grid/flex layout and can go anywhere the user wants on
// the page. This file is never edited when a template is added/changed/removed.

import { getTheme } from "./themes.js";

const PAGE_WIDTH = 735;
const PAGE_MIN_HEIGHT = 1040;

function esc(str) {
  return (str || "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}

function sectionHtml(theme, section, formData) {
  const rows = section.fields
    .map((f) => {
      const val = formData[f.id] && formData[f.id].toString().trim() ? esc(formData[f.id]) : "&nbsp;";
      return `
        <div style="display:grid;grid-template-columns:180px 14px 1fr;font-size:15px;line-height:1.5;padding:4px 0;">
          <span style="font-weight:700;">${esc(f.label)}</span>
          <span>:</span>
          <span>${val}</span>
        </div>`;
    })
    .join("");
  // Issue 9 & 10: a section with no fields (yet, or by design — e.g. a
  // "Photos" section that's just a heading) renders as the title plus its
  // own breathing room, never a "No fields added yet" placeholder line.
  return `
    <div style="margin-bottom:22px;min-height:${rows ? "0" : "14px"};">
      <h3 style="font-size:18px;font-weight:700;letter-spacing:.01em;margin:0 0 10px;padding-bottom:8px;border-bottom:2px solid ${theme.accent};color:${theme.accent};">${esc(section.title)}</h3>
      ${rows}
    </div>`;
}

// In-flow block of custom sections. Given `grid-column:1/-1` + `flex:0 0 100%`
// inline so that, if the template's root is CSS grid or flex (a few are),
// this block still spans full width as a new row instead of squeezing into
// one column/track.
function buildSectionsBlock(theme, sections, formData, { topBorder } = {}) {
  if (!sections.length) return "";
  return `
    <div style="grid-column:1/-1;flex:0 0 100%;width:100%;box-sizing:border-box;overflow-wrap:break-word;${
      // Issue 8: a plain, subtle solid rule instead of a dashed line — reads
      // as an intentional section divider rather than a placeholder/broken look.
      topBorder ? `margin-top:26px;padding-top:22px;border-top:1px solid ${theme.accent};` : ""
    }font-family:${theme.font};color:${theme.text};">
      ${sections.map((s) => sectionHtml(theme, s, formData)).join("")}
    </div>`;
}

// --- Aananda Digital watermark (live-preview only) ---
// This is purely a browser-preview deterrent against someone screenshotting
// a paid layout before paying. It does NOT need any "remove for the email"
// logic: the PDF that eventually gets emailed is generated by the BACKEND,
// directly from formData/schema (see backend/app/services/pdf_pipeline.py,
// not yet built) — a completely separate render pipeline from this DOM, so
// the watermark was simply never part of that file in the first place.
// IMPORTANT for whoever builds pdf_pipeline.py later: generate the PDF from
// formData/schema server-side (e.g. a template/PDF library), NOT by
// screenshotting or headless-rendering this preview page — doing the latter
// would carry this watermark into the paid file.
// mix-blend-mode keeps it readably faint on both light AND dark template
// themes (template_10/17/19 etc.) without needing a per-theme color choice.
const WATERMARK_TEXT = "AANANDA DIGITAL";
// Drop a real logo file at this path and it starts appearing automatically;
// until then, onerror below hides the broken-image icon so nothing looks off.
const WATERMARK_LOGO_SRC = "./src/assets/watermark-logo.png";

function watermarkTilesHtml(rotateDeg) {
  const cols = 3;
  const rows = 8;
  let tiles = "";
  for (let r = 0; r < rows; r += 1) {
    for (let c = 0; c < cols; c += 1) {
      const left = (c / cols) * 100 + (r % 2 === 0 ? 0 : 16);
      const top = (r / rows) * 100;
      tiles += `
        <div style="position:absolute;left:${left}%;top:${top}%;transform:rotate(${rotateDeg}deg);white-space:nowrap;display:flex;align-items:center;gap:5px;">
          <img src="${WATERMARK_LOGO_SRC}" alt="" style="width:20px;height:22px;object-fit:contain;" onerror="this.style.display='none'" />
          <span style="font-size:14px;font-weight:700;letter-spacing:.04em;font-family:Arial,sans-serif;">${WATERMARK_TEXT}</span>
        </div>`;
    }
  }
  return tiles;
}

function watermarkOverlayHtml() {
  return `
    <div class="bd-watermark-layer" style="
      position:absolute;inset:0;pointer-events:none;overflow:hidden;
      z-index:5000;color:rgba(120,120,120,.5);mix-blend-mode:difference;
    ">${watermarkTilesHtml(-28)}</div>`;
}

function photoShapeStyle(shape) {
  if (shape === "circle") return "border-radius:50%;";
  if (shape === "rect") return "border-radius:4px;";
  return "border-radius:8px;"; // square/default
}

// Issue 16: CSS filter presets for extra photos.
function photoFilterCss(filter) {
  switch (filter) {
    case "grayscale": return "filter:grayscale(1);";
    case "sepia": return "filter:sepia(0.8);";
    case "vintage": return "filter:sepia(0.35) contrast(1.05) brightness(1.05) saturate(1.15);";
    case "cool": return "filter:hue-rotate(-8deg) saturate(1.1) brightness(1.02);";
    case "soft": return "filter:contrast(0.95) brightness(1.05) saturate(0.9);";
    default: return "";
  }
}

// Canva-style on-photo edit menu: shape / border / filter / stacking /
// remove, all attached directly to the photo instead of living in the form.
// Exported so livePreview.js can read the same option lists when wiring inputs.
export const PHOTO_SHAPES = [["square", "Square"], ["circle", "Circle"], ["rect", "Rounded"]];
export const PHOTO_BORDER_STYLES = [["solid", "Solid"], ["dashed", "Dashed"], ["dotted", "Dotted"], ["double", "Double"], ["none", "None"]];
export const PHOTO_FILTERS = [["none", "None"], ["grayscale", "Grayscale"], ["sepia", "Sepia"], ["vintage", "Vintage"], ["cool", "Cool"], ["soft", "Soft"]];

function photoEditPanelHtml(theme, photo) {
  const bColor = photo.borderColor || theme.accent;
  return `
    <div class="bd-photo-edit-panel" data-photo-panel="${photo.id}" hidden>
      <div class="bd-panel-title">Style photo</div>
      <label>Shape
        <select data-style-photo="${photo.id}" data-style-key="shape">
          ${PHOTO_SHAPES.map(([v, l]) => `<option value="${v}" ${photo.shape === v ? "selected" : ""}>${l}</option>`).join("")}
        </select>
      </label>
      <label>Border
        <select data-style-photo="${photo.id}" data-style-key="borderStyle">
          ${PHOTO_BORDER_STYLES.map(([v, l]) => `<option value="${v}" ${(photo.borderStyle || "solid") === v ? "selected" : ""}>${l}</option>`).join("")}
        </select>
      </label>
      <label>Border width
        <input type="range" min="0" max="10" step="1" data-style-photo="${photo.id}" data-style-key="borderWidth" value="${photo.borderWidth ?? 3}" />
      </label>
      <label>Border color
        <input type="color" data-style-photo="${photo.id}" data-style-key="borderColor" value="${bColor}" />
      </label>
      <label>Filter
        <select data-style-photo="${photo.id}" data-style-key="filter">
          ${PHOTO_FILTERS.map(([v, l]) => `<option value="${v}" ${(photo.filter || "none") === v ? "selected" : ""}>${l}</option>`).join("")}
        </select>
      </label>
      <div class="bd-photo-edit-actions">
        <button type="button" data-photo-front="${photo.id}">&#8593; Bring to front</button>
        <button type="button" class="btn-danger" data-photo-remove="${photo.id}">Remove photo</button>
      </div>
    </div>`;
}

// Freeform, draggable/resizable photo overlay. `position:absolute` takes it
// completely out of the template's document flow (so it can never disturb a
// grid/flex layout and can never "escape" the page — it's always positioned
// relative to the nearest positioned ancestor, which is the page itself).
function photoOverlayHtml(theme, photo, formData) {
  const src = formData[photo.id];
  const shapeCss = photoShapeStyle(photo.shape);
  const x = photo.x ?? 40;
  const y = photo.y ?? 40;
  const w = photo.w ?? 120;
  const h = photo.h ?? 120;
  const filterCss = photoFilterCss(photo.filter);
  const inner = src
    ? `<img src="${src}" alt="${esc(photo.label)}" style="width:100%;height:100%;object-fit:cover;display:block;${shapeCss}${filterCss}" />`
    : `<div style="width:100%;height:100%;display:flex;align-items:center;justify-content:center;font-size:12px;text-align:center;opacity:.65;background:rgba(128,128,128,0.15);${shapeCss}">${esc(photo.label)}</div>`;

  // Issue 4 & 16: border style/width/color are per-photo and user-editable
  // (falls back to the template's own accent color/solid/3px when unset).
  const bStyle = photo.borderStyle || "solid";
  const bWidth = photo.borderWidth ?? 3;
  const bColor = photo.borderColor || theme.accent;
  const borderCss = bStyle === "none" ? "border:none;" : `border:${bWidth}px ${bStyle} ${bColor};`;

  return `
    <div class="bd-user-photo" data-photo-drag="${photo.id}" style="
      position:absolute;left:${x}px;top:${y}px;width:${w}px;height:${h}px;
      ${borderCss}box-sizing:border-box;cursor:move;pointer-events:auto;${shapeCss}
    ">
      ${inner}
      <div class="bd-user-photo-resize" data-photo-resize="${photo.id}"></div>
      <button type="button" class="bd-photo-edit-btn" data-photo-edit="${photo.id}" title="Edit photo">&#9998;</button>
      ${photoEditPanelHtml(theme, photo)}
    </div>`;
}

// Issues 3 & 5: each photo used to be wrapped in its own `inset:0` div —
// i.e. a full-page-covering box per photo. The LAST (newest) photo's
// invisible full-page box sat on top of everything in the stacking order
// and silently ate every pointer event across the whole page, including
// clicks/drags meant for older photos underneath — that's why an older
// photo became impossible to move/select once a newer one was added.
// Fix: no full-page wrapper at all. The layer itself stays pointer-events:none
// (so it never blocks the template under it) and only the actual photo
// boxes (sized to themselves, see `pointer-events:auto` above) accept clicks.
function photosOverlayHtml(theme, photos, formData) {
  if (!photos.length) return "";
  return `
    <div class="bd-user-photo-layer" style="position:absolute;inset:0;pointer-events:none;">
      ${photos.map((p) => photoOverlayHtml(theme, p, formData)).join("")}
    </div>`;
}

// A full continuation page (page 2, 3, ...), styled as its own sheet using
// the exact page-shell dimensions/background/border/font every template
// uses, so it reads as "the same biodata, next page".
function continuationPageHtml(theme, pageNumber, totalPages, photos, sections, formData, { watermark = true } = {}) {
  const borderCss = theme.border ? `border:${theme.border};` : `border:1px solid ${theme.accent};`;
  const isEmpty = !photos.length && !sections.length;
  return `
    <div class="bd-cont-page" style="
      position:relative;width:${PAGE_WIDTH}px;min-height:${PAGE_MIN_HEIGHT}px;margin:0 auto;
      box-sizing:border-box;padding:56px 60px;background:${theme.bg};color:${theme.text};
      font-family:${theme.font};${borderCss}
    ">
      <div style="position:absolute;top:22px;right:28px;font-size:11px;letter-spacing:.08em;text-transform:uppercase;opacity:.55;">
        Page ${pageNumber} of ${totalPages}
      </div>
      ${photosOverlayHtml(theme, photos, formData)}
      ${watermark ? watermarkOverlayHtml() : ""}
      ${
        isEmpty
          ? `<div style="font-size:13px;font-style:italic;opacity:.6;margin-top:60px;text-align:center;">No sections added to this page yet. Use "+ Add custom section" to fill it in.</div>`
          : buildSectionsBlock(theme, sections, formData, { topBorder: false })
      }
    </div>`;
}

// Returns { firstPagePhotosHtml, firstPageSectionsHtml, extraPageHtmls }.
// - firstPagePhotosHtml: absolute overlay, safe to inject ANYWHERE inside
//   the template's root div (position:absolute removes it from flow).
// - firstPageSectionsHtml: in-flow block, must be injected right before the
//   root div's closing tag.
// `watermark` defaults to true so every existing call site (the live
// preview) is completely unaffected. The backend's server-side PDF render
// is the ONE caller that passes { watermark: false } — see
// backend/render/render.mjs, which imports this exact file (not a copy) so
// the paid PDF can never drift from what this function produces here.
export function renderExtras(templateId, schema, formData, { watermark = true } = {}) {
  const theme = getTheme(templateId);
  const extraPhotos = schema.photos.slice(1); // photos[0] is always handled by the template itself
  const totalPages = schema.pages.length;
  const wm = watermark ? watermarkOverlayHtml() : "";

  const page1 = schema.pages[0];
  const page1Id = page1?.id;
  const page1CustomSections = (page1?.sections || []).filter((s) => s.custom);
  const page1Photos = extraPhotos.filter((p) => (p.page || page1Id) === page1Id);

  const firstPagePhotosHtml = photosOverlayHtml(theme, page1Photos, formData) + wm;
  const firstPageSectionsHtml = buildSectionsBlock(theme, page1CustomSections, formData, { topBorder: true });

  const extraPageHtmls = schema.pages.slice(1).map((page, i) => {
    const pagePhotos = extraPhotos.filter((p) => p.page === page.id);
    return continuationPageHtml(theme, i + 2, totalPages, pagePhotos, page.sections, formData, { watermark });
  });

  return { firstPagePhotosHtml, firstPageSectionsHtml, extraPageHtmls };
}